services:
    laravel:
        build:
            dockerfile: Dockerfile
        restart: always
        ports:
            - 127.0.0.1:8000:80
        volumes:
            - ./src:/app/src
        depends_on:
            - mysql
    caddy:
        image: caddy:alpine
        restart: unless-stopped
        cap_add:
          - NET_ADMIN
        ports:
            - 127.0.0.1:80:80
            - 127.0.0.1:443:443
            - 127.0.0.1:443:443/udp
        volumes:
            - $PWD/Caddyfile:/etc/caddy/Caddyfile
            - $PWD/src:/srv
            - bramm-caddy-data:/data
            - bramm-caddy-config:/config
    mysql:
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: "root"
        volumes:
            - bramm-db:/var/lib/mysql
        ports:
            - 127.0.0.1:3306:3306
    redis:
        restart: always
        image: redis:6
        command: redis-server --appendonly yes
        ports:
            - 127.0.0.1:6379:6379
    mailhog:
        image: mailhog/mailhog
        restart: always
        ports:
            - 127.0.0.1:1025:1025
            - 127.0.0.1:8025:8025
    phpmyadmin:
        image: phpmyadmin:latest
        restart: always
        ports:
            - 127.0.0.1:8001:80
        depends_on:
            - mysql
        environment:
            PMA_ABSOLUTE_URI: "https://phpmyadmin.dev/"
            PMA_HOST: mysql
            PMA_USER: root
            PMA_PASSWORD: "root"
            UPLOAD_LIMIT: 10G
            MEMORY_LIMIT: 2G
            MAX_EXECUTION_TIME: 600
volumes:
    bramm-db:
        driver: local
    bramm-caddy-data:
        driver: local
    bramm-caddy-config:
        driver: local
